version: 2.1

orbs:
  my-chrome-extension-orb: yoshihara/chrome-extension-orb@volatile

workflows:
  build_and_test:
    jobs:
      - my-chrome-extension-orb/test

  build_and_check_outdated_package:
    jobs:
      - my-chrome-extension-orb/check_outdated_npm_package
    triggers:
      - schedule:
          cron: "0 4 * * 0" # sunday at 13:00 (UTF+9)
          filters:
            branches:
              only:
                - master
